# Generated by Django 3.1.1 on 2020-09-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='club_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Club Name'),
        ),
    ]
