# Generated by Django 3.1.1 on 2020-09-10 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200909_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, verbose_name='Group Name')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.ManyToManyField(to='club.Team')),
            ],
        ),
    ]
